apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "pwa-weather.fullname" . }}-test-connection-shell-script"
data:
  test-connection.sh: |-
    #!/bin/sh
    wget -O {{ include "nextgen-app-deployment.fullname" . }}:{{ .Values.service.port }}